project_id = "gphmsrjiuiydmjezqijz"

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.send-fraud-alert]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false
